from xgboost import XGBClassifier
from flask import Flask, render_template, jsonify, request, send_file
from flask_login import LoginManager, login_required, current_user
import pandas as pd
import numpy as np
import joblib
import math
import os
import io

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from models import db, User, Threshold, DEFAULT_THRESHOLDS
from auth import auth_bp

app = Flask(__name__)
app.config["SECRET_KEY"] = "change-this-to-a-random-secret-string"
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///users.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db.init_app(app)

login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app.register_blueprint(auth_bp)

MODEL_DIR = "models"

# ============================================================
# NADINE'S MODELS (Fault Type classifier + RUL regressor)
# ============================================================
fault_clf = joblib.load(os.path.join(MODEL_DIR, "fault_classifier_model.pkl"))
rul_reg = joblib.load(os.path.join(MODEL_DIR, "rul_regressor_model.pkl"))
nadine_scaler = joblib.load(os.path.join(MODEL_DIR, "feature_scaler.pkl"))

# IMPORTANT: load the exact feature list saved by Nadine's notebook rather than
# hardcoding it here. Her FEATURE_COLS depends on all columns generated by
# engineer_features() minus the excluded label/target columns, and the exact
# set/order must match what the scaler and models were fit on.
NADINE_FEATURE_COLS = joblib.load(os.path.join(MODEL_DIR, "feature_columns.pkl"))
FAULT_LABEL_MAP = joblib.load(os.path.join(MODEL_DIR, "fault_label_map.pkl"))

# TODO: update this once Nadine's notebook finishes running. This must be set to
# the actual value printed by train_df["RUL_hours"].quantile(0.95) in her notebook
# (cell "9. Health Score"). Using a wrong reference value will scale Health_Score
# incorrectly across the whole dashboard.
RUL_REFERENCE_HOURS = 3000  # PLACEHOLDER - replace with Nadine's actual quantile value

# ============================================================
# SALSA'S MODEL (Severity condition: Normal/Warning/Critical/Failure)
# ============================================================
condition_clf = joblib.load(os.path.join(MODEL_DIR, "condition_classifier.joblib"))
salsa_scaler = joblib.load(os.path.join(MODEL_DIR, "condition_scaler.joblib"))

SALSA_FEATURE_COLS = [
    "Voltage_L1", "Voltage_L2", "Voltage_L3", "Frequency", "Power_Factor",
    "Temperature", "Vibration_X", "Vibration_Y", "Vibration_Z", "Rotational_Speed",
    "Voltage_Imbalance", "Vibration_Total", "Voltage_Mean", "RPM_Deviation"
]

# ============================================================
# RECOMMENDATION TABLE - must match Nadine's notebook exactly (5 fault types:
# Normal, Rotor Bar, Bearing Wear, Misalignment, Stator Winding). Do not add
# fault types that do not exist in the training data.
# ============================================================
RECOMMENDATION_TABLE = {
    "Normal": {
        "probable_cause": "-",
        "recommended_action": "Normal condition, continue routine monitoring"
    },
    "Rotor Bar": {
        "probable_cause": "Broken/cracked rotor bar due to repeated thermal stress or excessive starting frequency",
        "recommended_action": "Perform motor current signature analysis (MCSA) and schedule rotor inspection/teardown"
    },
    "Bearing Wear": {
        "probable_cause": "Inadequate lubrication, contamination, or bearing wear from excessive load",
        "recommended_action": "Re-lubricate or replace the bearing, check seal condition and shaft alignment"
    },
    "Misalignment": {
        "probable_cause": "Motor shaft misaligned with the driven load/coupling",
        "recommended_action": "Perform laser alignment check and correct the motor mounting position"
    },
    "Stator Winding": {
        "probable_cause": "Winding insulation degradation from repeated overheating or moisture contamination",
        "recommended_action": "Perform insulation resistance test (megger) and check the cooling system"
    }
}


# ============================================================
# FEATURE ENGINEERING - must be an EXACT copy of engineer_features() from
# Nadine's notebook. Column names and rolling windows must match precisely,
# because NADINE_FEATURE_COLS (loaded above) references these exact names.
# ============================================================
def engineer_features(data: pd.DataFrame, short_window=4, long_window=24) -> pd.DataFrame:
    data = data.copy()

    data["Vibration_RMS_Combined"] = np.sqrt(
        data["Vibration_X"]**2 + data["Vibration_Y"]**2 + data["Vibration_Z"]**2
    )

    v_mean = data[["Voltage_L1", "Voltage_L2", "Voltage_L3"]].mean(axis=1)
    v_max_dev = data[["Voltage_L1", "Voltage_L2", "Voltage_L3"]].sub(v_mean, axis=0).abs().max(axis=1)
    data["Voltage_Imbalance_Pct"] = (v_max_dev / v_mean) * 100

    feature_cols = ["Temperature", "Vibration_RMS_Combined", "Rotational_Speed", "Voltage_Imbalance_Pct"]

    grouped = data.groupby("motor_id")
    for col in feature_cols:
        data[f"{col}_roll_mean_short"] = grouped[col].transform(lambda s: s.rolling(short_window, min_periods=1).mean())
        data[f"{col}_roll_std_short"] = grouped[col].transform(lambda s: s.rolling(short_window, min_periods=1).std().fillna(0))
        data[f"{col}_roll_mean_long"] = grouped[col].transform(lambda s: s.rolling(long_window, min_periods=1).mean())
        data[f"{col}_delta"] = grouped[col].diff().fillna(0)

    return data


# ============================================================
# LOAD AND PREPARE DATA
# ============================================================
df = pd.read_csv("datasets/raw_sensor_new_data.csv")
df.rename(columns={"Timestamp": "timestamp", "Motor_ID": "motor_id"}, inplace=True)
df["timestamp"] = pd.to_datetime(df["timestamp"])
df = df.sort_values(["motor_id", "timestamp"]).reset_index(drop=True)

# Apply Nadine's rolling-window feature engineering (needed for fault type + RUL)
df = engineer_features(df)

# Apply Salsa's per-row derived features (needed for condition severity)
df["Voltage_Imbalance"] = df[["Voltage_L1", "Voltage_L2", "Voltage_L3"]].std(axis=1)
df["Vibration_Total"] = np.sqrt(df["Vibration_X"]**2 + df["Vibration_Y"]**2 + df["Vibration_Z"]**2)
df["Voltage_Mean"] = df[["Voltage_L1", "Voltage_L2", "Voltage_L3"]].mean(axis=1)
df["RPM_Deviation"] = abs(df["Rotational_Speed"] - 1500)

LATEST_ROWS = (
    df.groupby("motor_id", group_keys=False)
    .apply(lambda g: g.sample(n=1, random_state=42))
    .reset_index(drop=True)
    .sort_values("motor_id")
    .reset_index(drop=True)
)

ALL_MOTOR_IDS = sorted(df["motor_id"].unique().tolist())

STATUS_MAP = {
    "Normal": "Active",
    "Warning": "Idle",
    "Critical": "Maintenance",
    "Failure": "Stopped"
}

SENSOR_STATUS_MAP = {
    "Normal": "Normal",
    "Warning": "Watch",
    "Critical": "Critical",
    "Failure": "Critical"
}


# ============================================================
# HELPER FUNCTIONS
# ============================================================
def get_avg_voltage(row):
    return round((row["Voltage_L1"] + row["Voltage_L2"] + row["Voltage_L3"]) / 3.0, 1)


def get_vibration_rms(row):
    return round(math.sqrt(row["Vibration_X"]**2 + row["Vibration_Y"]**2 + row["Vibration_Z"]**2), 2)


def predict_row(row):
    """Combine Nadine's fault type + RUL prediction with Salsa's severity condition."""

    # ----- Nadine: fault type + RUL -----
    nadine_features = row[NADINE_FEATURE_COLS].values.reshape(1, -1)
    nadine_scaled = nadine_scaler.transform(nadine_features)

    fault_pred_raw = fault_clf.predict(nadine_scaled)[0]
    if isinstance(fault_clf, XGBClassifier):
        fault_pred = FAULT_LABEL_MAP[int(fault_pred_raw)]
    else:
        fault_pred = str(fault_pred_raw)
    rul_pred = float(rul_reg.predict(nadine_scaled)[0])

    health_score = max(0.0, min(100.0, (rul_pred / RUL_REFERENCE_HOURS) * 100))
    failure_probability = round(100 - health_score, 1)

    # ----- Salsa: severity condition -----
    salsa_features = row[SALSA_FEATURE_COLS].values.reshape(1, -1)
    salsa_scaled = salsa_scaler.transform(salsa_features)
    condition_label = condition_clf.predict(salsa_scaled)[0]

    # ----- Recommendation lookup (based on fault type, not severity) -----
    fault_info = RECOMMENDATION_TABLE.get(fault_pred, RECOMMENDATION_TABLE["Normal"])

    rul_display = min(rul_pred, 5000)
    rul_days = rul_pred / 24
    if rul_days <= 30:
        risk_window_label = f"Estimated within {round(rul_days)} days"
    else:
        risk_window_label = "Beyond 30-day horizon"

    return {
        "condition_label": condition_label,
        "fault_type": fault_pred,
        "probable_cause": fault_info["probable_cause"],
        "recommendation": fault_info["recommended_action"],
        "health_score": round(health_score, 1),
        "failure_probability": failure_probability,
        "rul_hours": round(rul_display, 1),
        "risk_window_label": risk_window_label
    }


def get_row_for_device(device_id):
    match = LATEST_ROWS[LATEST_ROWS["motor_id"] == device_id]
    if match.empty:
        return LATEST_ROWS.iloc[0]
    return match.iloc[0]


# ============================================================
# ROUTES
# ============================================================
@app.route("/")
@login_required
def index():
    return render_template(
        "index.html",
        is_admin=current_user.is_admin,
        username=current_user.username
    )


@app.route("/api/devices")
@login_required
def get_devices():
    return jsonify({"devices": ALL_MOTOR_IDS})


@app.route("/api/status")
@login_required
def get_status():
    device_id = request.args.get("device", ALL_MOTOR_IDS[0])
    row = get_row_for_device(device_id)
    prediction = predict_row(row)

    return jsonify({
        "health_score": prediction["health_score"],
        "rul_hours": prediction["rul_hours"],
        "failure_probability": prediction["failure_probability"],
        "risk_window_label": prediction["risk_window_label"],
        "recommendation": prediction["recommendation"],
        "probable_cause": prediction["probable_cause"],
        "fault_type": prediction["fault_type"],
        "false_alarm_rate": 0.02,
        "temperature": float(row["Temperature"]),
        "vibration": get_vibration_rms(row),
        "current": get_avg_voltage(row),
        "pressure": float(row["Rotational_Speed"]),
        "device": str(row["motor_id"])
    })


@app.route("/api/history")
@login_required
def get_history():
    device_id = request.args.get("device", ALL_MOTOR_IDS[0])
    points = int(request.args.get("points", 20))

    motor_df = df[df["motor_id"] == device_id].sort_values("timestamp").tail(points)

    return jsonify({
        "labels": motor_df["timestamp"].dt.strftime("%H:%M").tolist(),
        "temperature": motor_df["Temperature"].round(1).tolist(),
        "vibration": [get_vibration_rms(row) for _, row in motor_df.iterrows()],
        "voltage": [get_avg_voltage(row) for _, row in motor_df.iterrows()],
        "rpm": motor_df["Rotational_Speed"].round(1).tolist()
    })


@app.route("/api/alerts")
@login_required
def get_alerts():
    device_id = request.args.get("device")
    alerts = []
    rows = LATEST_ROWS if device_id is None else LATEST_ROWS[LATEST_ROWS["motor_id"] == device_id]

    for _, row in rows.iterrows():
        prediction = predict_row(row)
        label = prediction["condition_label"]
        fault = prediction["fault_type"]
        device_id_str = str(row["motor_id"])

        if label == "Critical":
            alerts.append({
                "type": "warning",
                "icon": "fa-temperature-high",
                "title": f"Critical Pattern Detected on {device_id_str}",
                "description": f"{fault}: {prediction['probable_cause']}",
                "time": "Just now",
                "action": "Investigate",
                "device_id": device_id_str
            })
        elif label == "Failure":
            alerts.append({
                "type": "warning",
                "icon": "fa-circle-exclamation",
                "title": f"Failure Risk on {device_id_str}",
                "description": f"{fault}: {prediction['probable_cause']}",
                "time": "Just now",
                "action": "Investigate",
                "device_id": device_id_str
            })
        elif label == "Warning":
            alerts.append({
                "type": "info",
                "icon": "fa-chart-line",
                "title": f"Early Degradation Signs on {device_id_str}",
                "description": f"{fault}: {prediction['probable_cause']}",
                "time": "Just now",
                "action": "View Plan",
                "device_id": device_id_str
            })

    if not alerts:
        alerts.append({
            "type": "safe",
            "icon": "fa-shield",
            "title": "All Motors Normal",
            "description": "No degradation patterns detected across monitored motors.",
            "time": "Just now",
            "action": None,
            "device_id": None
        })

    return jsonify(alerts[:20])


@app.route("/api/motors")
@login_required
def get_motors():
    motors = []

    for _, row in LATEST_ROWS.iterrows():
        prediction = predict_row(row)
        status = STATUS_MAP.get(prediction["condition_label"], "Active")

        motors.append({
            "id": str(row["motor_id"]),
            "name": f"Induction Motor {row['motor_id']}",
            "location": "Production Line",
            "status": status,
            "health_score": int(round(prediction["health_score"])),
            "rul_hours": int(prediction["rul_hours"]),
            "fault_type": prediction["fault_type"],
            "last_update": row["timestamp"].strftime("%Y-%m-%d %H:%M")
        })

    summary = {
        "total": len(motors),
        "active": sum(1 for m in motors if m["status"] == "Active"),
        "idle": sum(1 for m in motors if m["status"] == "Idle"),
        "maintenance": sum(1 for m in motors if m["status"] == "Maintenance"),
        "stopped": sum(1 for m in motors if m["status"] == "Stopped"),
    }

    return jsonify({"motors": motors, "summary": summary})


@app.route("/api/sensors")
@login_required
def get_sensors():
    readings = []

    for _, row in LATEST_ROWS.iterrows():
        prediction = predict_row(row)
        status = SENSOR_STATUS_MAP.get(prediction["condition_label"], "Normal")

        readings.append({
            "motor_id": str(row["motor_id"]),
            "motor_name": f"Induction Motor {row['motor_id']}",
            "temperature": float(row["Temperature"]),
            "vibration": get_vibration_rms(row),
            "current": get_avg_voltage(row),
            "pressure": float(row["Rotational_Speed"]),
            "status": status,
            "fault_type": prediction["fault_type"]
        })

    return jsonify(readings)


@app.route("/api/logs")
@login_required
def get_logs():
    logs = []

    for i, row in LATEST_ROWS.iterrows():
        prediction = predict_row(row)
        label = prediction["condition_label"]
        fault = prediction["fault_type"]

        icon_map = {
            "Normal": "fa-shield",
            "Warning": "fa-temperature-high",
            "Critical": "fa-circle-exclamation",
            "Failure": "fa-circle-exclamation"
        }
        type_map = {
            "Normal": "safe",
            "Warning": "warning",
            "Critical": "critical",
            "Failure": "critical"
        }
        title_map = {
            "Normal": "Normal Operating Pattern",
            "Warning": "Early Degradation Pattern Detected",
            "Critical": "Critical Degradation Pattern Detected",
            "Failure": "Failure Risk Pattern Detected"
        }

        logs.append({
            "id": i,
            "type": type_map.get(label, "safe"),
            "icon": icon_map.get(label, "fa-shield"),
            "title": title_map.get(label, "Status Update"),
            "description": f"Fault: {fault}. RUL: {int(prediction['rul_hours'])} hours. {prediction['probable_cause']}",
            "device": f"Induction Motor {row['motor_id']}",
            "device_id": str(row["motor_id"]),
            "time": row["timestamp"].strftime("%Y-%m-%d %H:%M")
        })

    return jsonify(logs)


@app.route("/api/settings", methods=["GET", "POST"])
@login_required
def update_settings():
    threshold = Threshold.query.first()

    if request.method == "GET":
        return jsonify({
            "temperature": threshold.temperature,
            "vibration": threshold.vibration,
            "current_deviation": threshold.current_deviation,
            "pressure": threshold.pressure
        })

    if not current_user.is_admin:
        return jsonify({"error": "Forbidden: admin access required"}), 403

    payload = request.get_json()
    threshold.temperature = payload.get("temperature", threshold.temperature)
    threshold.vibration = payload.get("vibration", threshold.vibration)
    threshold.current_deviation = payload.get("current_deviation", threshold.current_deviation)
    threshold.pressure = payload.get("pressure", threshold.pressure)
    db.session.commit()

    return jsonify({"message": "Settings saved."})


@app.route("/api/settings/reset", methods=["POST"])
@login_required
def reset_settings():
    if not current_user.is_admin:
        return jsonify({"error": "Forbidden: admin access required"}), 403

    threshold = Threshold.query.first()
    threshold.temperature = DEFAULT_THRESHOLDS["temperature"]
    threshold.vibration = DEFAULT_THRESHOLDS["vibration"]
    threshold.current_deviation = DEFAULT_THRESHOLDS["current_deviation"]
    threshold.pressure = DEFAULT_THRESHOLDS["pressure"]
    db.session.commit()

    return jsonify(DEFAULT_THRESHOLDS)


@app.route("/api/report", methods=["POST"])
@login_required
def generate_report():
    payload = request.get_json()
    selected_motors = payload.get("motors", ALL_MOTOR_IDS)
    selected_fields = payload.get("fields", ["temperature", "vibration", "voltage", "rpm"])
    include_predictions = payload.get("include_predictions", True)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Heading1"], textColor=colors.HexColor("#f97316"))

    elements = []
    elements.append(Paragraph("Winteq Predictive Maintenance Report", title_style))
    elements.append(Paragraph(f"Generated by: {current_user.username}", styles["Normal"]))
    elements.append(Paragraph(f"Motors included: {', '.join(selected_motors)}", styles["Normal"]))
    elements.append(Spacer(1, 0.5*cm))

    for device_id in selected_motors:
        row = get_row_for_device(device_id)
        prediction = predict_row(row)

        elements.append(Paragraph(f"Motor: {device_id}", styles["Heading2"]))

        table_data = [["Field", "Value"]]
        field_map = {
            "temperature": ("Temperature (C)", float(row["Temperature"])),
            "vibration": ("Vibration RMS (mm/s)", get_vibration_rms(row)),
            "voltage": ("Voltage Avg (V)", get_avg_voltage(row)),
            "rpm": ("Rotational Speed (RPM)", float(row["Rotational_Speed"])),
        }
        for f in selected_fields:
            if f in field_map:
                label, value = field_map[f]
                table_data.append([label, str(value)])

        if include_predictions:
            table_data.append(["Predicted Condition", prediction["condition_label"]])
            table_data.append(["Fault Type", prediction["fault_type"]])
            table_data.append(["Health Score", f"{prediction['health_score']}%"])
            table_data.append(["Estimated RUL", f"{prediction['rul_hours']} hours"])
            table_data.append(["Failure Probability", f"{prediction['failure_probability']}%"])
            table_data.append(["Risk Window", prediction["risk_window_label"]])
            table_data.append(["Probable Cause", prediction["probable_cause"]])
            table_data.append(["Recommendation", prediction["recommendation"]])

        t = Table(table_data, colWidths=[8*cm, 8*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a1a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(t)

        motor_hist = df[df["motor_id"] == device_id].sort_values("timestamp").tail(30)
        if not motor_hist.empty and "temperature" in selected_fields:
            fig, ax = plt.subplots(figsize=(6, 2.2))
            ax.plot(range(len(motor_hist)), motor_hist["Temperature"], color="#f97316")
            ax.set_title(f"{device_id} - Temperature Trend", fontsize=9)
            ax.set_xticks([])
            img_buf = io.BytesIO()
            plt.tight_layout()
            fig.savefig(img_buf, format="png", dpi=120)
            plt.close(fig)
            img_buf.seek(0)
            elements.append(Spacer(1, 0.3*cm))
            elements.append(Image(img_buf, width=14*cm, height=4*cm))

        elements.append(Spacer(1, 0.8*cm))

    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        mimetype="application/pdf",
        as_attachment=True,
        download_name="winteq_maintenance_report.pdf"
    )


with app.app_context():
    db.create_all()

    if not Threshold.query.first():
        db.session.add(Threshold())
        db.session.commit()
        print("Default thresholds created.")

    if not User.query.filter_by(role="admin").first():
        admin = User(username="admin", email="admin@local", role="admin")
        admin.set_password("admin123")  # CHANGE THIS AFTER FIRST LOGIN
        db.session.add(admin)
        db.session.commit()
        print("Default admin created -> username: admin | password: admin123")


if __name__ == "__main__":
    app.run(debug=True, port=5000)